### ISSUE TITLE
Retweets snippet code pulling username instead of screen name

### ISSUE THREAD

**Issue by pmacswebteam** [qodo/TwitterX#13]
It seems like the snippet code for retweets is pulling and linking the username:

 $toPlaceholderPrefix . 'text' => 'RT @' . $j->retweeted_status->user->name . ': ' . $j->retweeted_status->text

...instead of pulling and linking the screenname:

 $toPlaceholderPrefix . 'text' => 'RT @' . $j->retweeted_status->user->screen_name . ': ' . $j->retweeted_status->text

Can this be fixed and released as an update for TwitterX? Right now it is resulting in broken twitter handle link when choosing to display retweets.

**Comment by qodo** [comment]
Just updated this and releasing new version today. Thanks very much for reporting this! :)
